port = 3000
debug = true
domain = "localhost:3000"

[database]
host = "localhost"
port = 5432
database = "scrobz"
user = "postgres"
password = "postgres"

[oauth_provider]
client_id = "scrobbz"
client_secret = "todo"
provider = "todo"
user_info_url = "todo"
token_url = "todo"
auth_url=  "todo"