[package]
name = "elder-scrobz-model"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
elder-scrobz-db.workspace = true
elder-scrobz-settings.workspace = true
utoipa.workspace = true
chrono.workspace = true
once_cell.workspace = true
